### ISSUE TITLE
toSBML() : Not valid exported file

### ISSUE THREAD

**Issue by Ahmed7emdan** [saezlab/CellNOptR#14]
Hi, 
I used 
`network <- readSIF("./ubiquitine_signalling.sif")
toSBML(network, file, bitString = c(rep(1,length(network))),version=c("standard","cellnopt"))`
to generate a qual file and tried to validate the the exported Sbml-qual file on [SBML validator](http://sbml.org/Facilities/Validator/index.jsp) but it is not valid SBML. How can we obtain a valid file
Thanks in advance

**Comment by gabora** [comment]
Hi, 
please note that there is a difference between `SBML` and `SBMLqual`.

I was testing with the example SBML qual file from [here](http://www.colomoto.org/formats/sbml-qual.html) and it reports it as invalid. So I think this validator is not supporting SBML**qual** format. 

Another possible problem could be that you should not use `length(network)`, but `length(network$reacID)` instead. Please check the manual of `toSBML()` function. 

best,
Attila

**Comment by Ahmed7emdan** [comment]
Thanks a lot for replying. 
I would like to ask if we have a negative reaction between inputs and the out put in SIF format 
how toSBML( ) translate this reaction type to negative, because the reaction types were all translated to positive as example
` <qual:input qual:id="theta_t54_re1" qual:qualitativeSpecies="re1" qual:transitionEffect="none" **qual:sign="positive"** qual:thresholdLevel="1"/>`
Thanks a lot

**Comment by gabora** [comment]
Hi, 

the inhibitions (negative reactions) in the SIF file are encoded with -1. 
for example: 
`Akt -1 Mek`

check the sif, or plot it with `plotModel()`: the inhibition is shown with red, T-shaped arrow: 
![image](https://user-images.githubusercontent.com/3891745/68571011-3de5d500-0462-11ea-8f35-4bd4c0682480.png)

when I import a network containing this reaction and then export to an SBML file, I get the correct sign: 
`<qual:input  qual:id="theta_t10_Akt" qual:qualitativeSpecies="Akt" qual:transitionEffect="none" qual:sign="negative" qual:thresholdLevel="1"/>`
I think, something should be wrong in the SIF file.

**Comment by Ahmed7emdan** [comment]
Thanks a lot this will be helpful
