### ISSUE TITLE
TypeError in Python CellNetOpt Tutorial

### ISSUE THREAD

**Issue by VitaminBrad** [saezlab/CellNOptR#17]
Hello!

In following the Quick Start tutorial found [here](https://pythonhosted.org/cno/quickstart.html), I came across the following error when trying to use the `add_edge()` function:

> TypeError                                 Traceback (most recent call last)
> <ipython-input-7-a2108586bcf9> in <module>()
>       1 from cno import CNOGraph
>       2 c1 = CNOGraph()
> ----> 3 c1.add_edge("A","B", link="+")
>       4 c1.add_edge("A","C", link="-")
>       5 c1.plot()
> 
> /home/benglish/anaconda3/envs/cno/lib/python2.7/site-packages/cno/io/cnograph.pyc in add_edge(self, u, v, attr_dict, **attr)
>     734         else:
>     735             attr = self.get_default_edge_attributes(**attr)
> --> 736             super(CNOGraph, self).add_edge(u, v, attr_dict, **attr)
>     737 
>     738     def clear(self):
> 
> TypeError: add_edge() takes exactly 3 arguments (8 given)

The add_edge function is only being given 3 arguments in the code, so I'm very confused why or how this is happening. 

Thanks!!!

**Comment by VitaminBrad** [comment]
Additionally, the following error occurs when I try

`from cno import XMIDAS, cnodata
m = XMIDAS(cnodata("MD-ToyPB.csv"))
m.plot()`

>  /home/benglish/anaconda3/envs/cno/lib/python2.7/site-packages/cno/io/midas.py:268: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
>   value_signals = _data[df_dv.columns].as_matrix()
> /home/benglish/anaconda3/envs/cno/lib/python2.7/site-packages/cno/io/midas.py:320: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
> For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
>   copy=True)
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-9-7dbec17996fb> in <module>()
>       1 from cno import XMIDAS, cnodata
> ----> 2 m = XMIDAS(cnodata("MD-ToyPB.csv"))
>       3 m.plot()
> 
> /home/benglish/anaconda3/envs/cno/lib/python2.7/site-packages/cno/io/midas.pyc in __init__(self, filename, cellLine, verbose, exclude_rows)
>     616             pass
>     617         elif isinstance(filename, str):
> --> 618             self.read()
>     619             self.create_empty_simulation()
>     620             self.errors = self.sim.copy()
> 
> /home/benglish/anaconda3/envs/cno/lib/python2.7/site-packages/cno/io/midas.pyc in read(self)
>     127         # from the data, build up the experiment and data dataframes
>     128         self.logging.debug(" - Initialising")
> --> 129         self._init()
>     130         self.logging.debug(" - Data loaded")
>     131 
> 
> /home/benglish/anaconda3/envs/cno/lib/python2.7/site-packages/cno/io/midas.pyc in _init(self)
>     326 
>     327         self.df = pd.DataFrame(value_signals, index=index, columns=names_species)
> --> 328         self.df = self.df.sortlevel(["experiment"])
>     329         self.df = self.df.sort_index(axis=1) # sort the species
>     330 
> 
> /home/benglish/anaconda3/envs/cno/lib/python2.7/site-packages/pandas/core/generic.pyc in __getattr__(self, name)
>    5065             if self._info_axis._can_hold_identifiers_and_holds_name(name):
>    5066                 return self[name]
> -> 5067             return object.__getattribute__(self, name)
>    5068 
>    5069     def __setattr__(self, name, value):
> 
> AttributeError: 'DataFrame' object has no attribute 'sortlevel'
> 

Perhaps they're both related to a larger incompatibility issue, I'm facing?
I'm running python 2.7 on an anaconda environment in jupyter notebook on a Scientific Linux.
Thanks again!!

**Comment by gabora** [comment]
Hi, 

thanks for writing. This is the R-version of CellNOptR, and unfortunately, I cannot provide support for the python version.
 
You could try to get help from here: 
https://github.com/cellnopt/cellnopt

We planned to have an updated python version in the near future, but it will be linked to the R-package under the hood. 

best,
attila
