### ISSUE TITLE
Problem with CNORFeeder

### ISSUE THREAD

**Issue by ucsdwxu** [saezlab/CellNOptR#4]
I am writing to seek a help in one problem that I am having now when following the CNORFeeder tutorial document. After first 4 sections it was fine but when the last section on "4.5 - Training", I could not get a plot which is the same as the example given in Figure 3 left and also the plot of the model fit to experimental data as well (Figure 3 right). I followed exactly the command shown in the document by pasting to my console but tried many times and could not get the correct as shown in the document. Would you please be able to help by advising me what could go wrong?

**Comment by enio23** [comment]
Hello,

After a little discussion we suggest to maybe let the training part run for longer (increase popSize, maxGens and maxTime) and point out that the one shown in the vignette is the "best model" for that run, but being a stochastic optimisation algorithm the" best model" might change every time, so please look at the family or resulting models instead.

Please let us know at anytime how the solution proposed worked for you and at anytime or for any other issues do not hesitate to contact us, we are more than ready to help.

Cheers,
Enio

**Comment by ucsdwxu** [comment]
Hi Enio,

Many thanks for your advice. I will try again following the suggestion and will let you know about how it goes.

Cheers,
Weijun

**Comment by gabora** [comment]
Hi Weijun,

sorry for the late answer, I just remembered this thread when I saw Enio's answer. 

The default values for the optimisation (`gaBinaryT1`) in CellNOptR are 
`popSize = 50, maxTime = 60, maxGens = 500, stallGenMax = 100` -- this works fairly good for small cases, like 8-10 nodes. For larger models, with 50-100 nodes we typically run the optimisation over a few hours. And we run it many times to have a better chance to find the global optima. 

I think the settings in the Feeder package' tutorial is very low to avoid long vignette compilation time. 
The Figure was probably generated once with longer optimisation, then saved as a pdf and imported for the vignette.

So please consider the above numbers as minimum requirements for the optimisation part.
And please let us know how it goes and if we can help you more. 
best,
Attila

**Comment by ucsdwxu** [comment]
Dear Attila,
Appreciate so much for the explanation on the settings and parameters adjustment. I will definitely try your suggestion and feedback to you.
Have a nice day.
Cheers,
Weijun
