### ISSUE TITLE
Problem with CytoCopter 

### ISSUE THREAD

**Issue by ucsdwxu** [saezlab/CellNOptR#7]
Hi, 

I am reporting another problem here hopefully to gain some advice from you. I tried the tutorial on CytoCopter section but until the last step for model optimisation stage, after the optimisation was done, the remodelled network plot appearing in Cytoscape is not the same type of format shown in the tutorial, instead, the way it was shown is the same as when I just loaded the original sif file before the preprocess step (e.g. all are blue color boxes, but no white box, no green cues and no red color to indicate the inhibited node) , although the AND or OR link has been added. 

Thank you for your kind help again.

**Comment by gabora** [comment]
Hello,

could you check if the correct style (Cytocopter) is loaded?
![image](https://user-images.githubusercontent.com/3891745/48299582-1ff03800-e4cf-11e8-98b9-38e453c1ab54.png)

**Comment by ucsdwxu** [comment]
Hi Attila,

Now it works by clicking to Cytocopter style. Thanks again for the guide.

Best regards,
Weijun
